language: php
php:
  - '7.1'
cache:
  yarn: true
  directories:
    - node_modules
# TODO: CI_ENVをセットする
before_install:
  - nvm install 'node'
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn install
install:
  - composer install
  - yarn install
script:
  - yarn build
  - mkdir -p build/logs
  - yarn test
  - phpunit --coverage-clover ../../build/logs/clover.xml 
